SELECT * FROM customer limit 21

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as Revenue
FROM customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT purchase_amount , customer_id 
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(avg(review_rating :: numeric),2) as "Average Review Rating"
FROM customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(avg(purchase_amount),2)
FROM customer
WHERE shipping_type in('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status , COUNT (customer_id) AS Total_Customer,
ROUND(SUM(purchase_amount),2) AS Total_spend,
ROUND(avg(purchase_amount),2) AS Average_spend
FROM customer
GROUP BY subscription_status
ORDER BY Total_spend, Average_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY item_purchased 
limit 5;


--Q7. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status , COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status ;



--Q8. What is the revenue contribution of each age group? 
SELECT age_group , ROUND(SUM(purchase_amount),2) AS total_spend
FROM customer
GROUP BY age_group
ORDER BY total_spend desc;
